### ISSUE TITLE
训练图片大小的问题

### ISSUE THREAD

**Issue by liang233** [nicholasly/TFN-Dehazing#2]
你好，我想问下，你们train的时候，是用ITS 整个640*480图训练的,还是像reside 那个数据集论文里取128*128 patch进行训练的？我觉得reside那个评判标准里训练图片和测试图片大小不太一致，可能会导致PSNR变差，谢谢

**Comment by nicholasly** [comment]
RESIDE室内图测试集是有问题的，所以我自己从ITS抽了990张图片出来做测试集。我一张图训练大小设置为512x512。

**Comment by liang233** [comment]
好的，谢谢，室内测试集可以采用这个https://pan.baidu.com/s/16IInkL-KVJWfME2iBBCsAA，这个没有白边

**Comment by nicholasly** [comment]
感谢感谢
